//AUTO GENERATED
//TODO:THESE ARE HARDCODED --- MUST CHANGE TO CONFIGURE SCRIPT
#define BAP_HOST_FILE "hostfile"
#define BAP_TOIL "bap-0.7/utils/toil"
#define BAP_TEMP_FILE "temptemp"
#define BAP_HOST_FILE_TEXT_START 0x000000b0
#define BAP_HOST_FILE_TEXT_ADDR 0x128
